// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    IconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ProBreadcrumb: typeof import('element-pro-components')['ProBreadcrumb']
    ProForm: typeof import('element-pro-components')['ProForm']
    ProLayout: typeof import('element-pro-components')['ProLayout']
    ProTabs: typeof import('element-pro-components')['ProTabs']
    RichEditor: typeof import('./src/components/RichEditor.vue')['default']
  }
}

export { }
