// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DashboardCard: typeof import('./src/components/DashboardCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ElIconRefresh: typeof import('@element-plus/icons-vue')['Refresh']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTag: typeof import('element-plus/es')['ElTag']
    ProBreadcrumb: typeof import('element-pro-components')['ProBreadcrumb']
    ProCard: typeof import('element-pro-components')['ProCard']
    ProColumnSetting: typeof import('element-pro-components')['ProColumnSetting']
    ProCrud: typeof import('element-pro-components')['ProCrud']
    ProDescriptions: typeof import('element-pro-components')['ProDescriptions']
    ProForm: typeof import('element-pro-components')['ProForm']
    ProLayout: typeof import('element-pro-components')['ProLayout']
    ProTable: typeof import('element-pro-components')['ProTable']
    ProTabs: typeof import('element-pro-components')['ProTabs']
    RichEditor: typeof import('./src/components/RichEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
